### ISSUE TITLE
Add pandapower to LF Energy landscape page?

### ISSUE THREAD

**Issue by nicorikken** [e2nIEE/pandapower#1332]
For the LFEnergy there is a [landscape page](https://landscape.lfenergy.org/) that maps software projects in an high-level architecture. More on this technical architecture is available on the [website](https://www.lfenergy.org/projects/functional-architecture/) or in this video recording of the [Technical Architecture Workshop in 2020](https://youtu.be/FLhWR_HefZo?t=190). Of course the LFEnergy are represented here, but also other software projects that exist in the same category, both open source or proprietary software.

PandaPower is not on this landscape page, despite being used quite a lot and even being open source. It makes sense to add PandaPower there. I'm happy to make a pull-request to the [landschape git repository](https://github.com/lf-energy/lfenergy-landscape) but decided to first come here to discuss it with you.

I was thinking of adding the following data to the [landscape.yml](https://github.com/lf-energy/lfenergy-landscape/blob/main/landscape.yml) file, under the section **System Management > Power System Calculation**:
```yaml
          - item:
            name: pandapower
            description: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation. 
            homepage_url: http://www.pandapower.org/
            repo_url: https://github.com/e2nIEE/pandapower
            logo: pandapower.svg # from http://www.pandapower.org/images/pp.svg
            twitter: # none I guess?
            crunchbase: # none I guess, as it is a joint effort?
```

What do you think of this idea and details? Would you like to file the PR yourself, or should I do it?
